### ISSUE TITLE
ахуеть спасибо папаша

### ISSUE THREAD

**Issue by reyawake** [Redacted00/BR_MapTemplate#1]
### ахуеть спасибо папаша
**BrickRigs could not be compiled. Try rebuilding from source manually**

**Comment by Krim1o** [comment]
теперь я могу сделать карту, темплайт раньше не работал

**Comment by Redacted00** [comment]
<img width="585" alt="Screenshot_17" src="https://user-images.githubusercontent.com/38829120/128481615-68c96ea7-4985-4700-9273-82a60e268971.png">
