### ISSUE TITLE
Застрял в режиме спектатора

### ISSUE THREAD

**Issue by reyawake** [Redacted00/BR_MapTemplate#2]
**редуктер хелп, ты знаешь в чём дело?**

**Comment by Redacted00** [comment]
Ты создал карту на эксперементалке или на обычной версии?

**Comment by reyawake** [comment]
Обычная новая

**Comment by Redacted00** [comment]
Можешь скинуть скрин с карты?

**Comment by Krim1o** [comment]
![image](https://user-images.githubusercontent.com/83013905/128599033-6cb88cdb-0b39-4cc9-a09c-affe39dacc94.png)

**Comment by reyawake** [comment]
![da](https://user-images.githubusercontent.com/83013905/128599071-8b17a32a-3c2a-4125-ae02-921e88bc95ec.png)

**Comment by Redacted00** [comment]
Ты поставил BP_VehicleEditor и BP_Editor_Small на карту?

**Comment by reyawake** [comment]
Блина мина не

**Comment by reyawake** [comment]
Минутку

**Comment by reyawake** [comment]
Кста зря ты хамарин скачал xD

**Comment by reyawake** [comment]
Все работает. Только спавнится в воздухе xD

**Comment by reyawake** [comment]
Нельзя посмотреть как будут здания выглядеть в едиторе?

**Comment by reyawake** [comment]
![20210808220820_1](https://user-images.githubusercontent.com/83013905/128633066-2652b884-7fff-419d-8a11-a8a0931c71b2.jpg)
### 

> _**расия**_

**Comment by Redacted00** [comment]
Проблема решена
